[package]
name = "my_game"
version = "0.1.0"
authors = ["mishazawa"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agb = "0.25.0"
agb_tracker = "0.25.0"
num-traits = { version = "0.2.19", default-features = false }

[profile.dev]
opt-level = 3
debug = true

[profile.dev.build-override]
opt-level = 3

[profile.release]
opt-level = 3
lto = "fat"
debug = true
